#!/usr/bin/env bash
# =====================================================================================
# Prefetch every remote asset to a shared cache OUTSIDE $HOME.  RUN ON A LOGIN NODE.
#
#   ADARQ_CACHE=$WORK/adarq-cache bash scripts/prefetch_assets.sh
#
# Cineca Leonardo (and most HPC sites): login nodes have internet, COMPUTE NODES DO NOT,
# and $HOME has a small quota that model weights will blow through. So every download
# happens here, once, into $ADARQ_CACHE — then compute nodes run fully offline against
# that directory.
#
# Downloads:
#   * openai/clip-vit-base-patch32   real CLIP vision tower (~600 MB)
#   * COCO val2017 sample            real photographs, saved as .jpg
#   * (optional) --gated             Qwen2.5-VL / FLUX.1-dev, needs `hf auth login`
#
# On the compute node, source the generated env file and everything resolves locally:
#   source $ADARQ_CACHE/adarq_env.sh      # sets HF_HOME + HF_HUB_OFFLINE=1
# =====================================================================================
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NUM_IMAGES="${NUM_IMAGES:-64}"
CLIP_MODEL="${CLIP_MODEL:-openai/clip-vit-base-patch32}"
WANT_GATED=0
[ "${1:-}" = "--gated" ] && WANT_GATED=1

# -- 1. cache location must be explicit and must not sit in $HOME ----------------------
if [ -z "${ADARQ_CACHE:-}" ]; then
  cat >&2 <<'EOF'
ADARQ_CACHE is not set. Point it at large shared storage, NOT $HOME:

  export ADARQ_CACHE=$WORK/adarq-cache      # Cineca: $WORK or $SCRATCH
  bash scripts/prefetch_assets.sh

Refusing to guess a location: defaulting to $HOME would silently fill your home quota.
EOF
  exit 1
fi
case "$(readlink -m "$ADARQ_CACHE")/" in
  "$(readlink -m "$HOME")"/*)
    echo "ADARQ_CACHE ($ADARQ_CACHE) is inside \$HOME. Model weights belong on \$WORK or" >&2
    echo "\$SCRATCH — \$HOME quotas are small and shared. Aborting." >&2
    exit 1 ;;
esac

mkdir -p "$ADARQ_CACHE"
export HF_HOME="$ADARQ_CACHE/hf"
export HF_HUB_CACHE="$HF_HOME/hub"
export TRANSFORMERS_CACHE="$HF_HOME/transformers"   # legacy readers
export HF_HUB_OFFLINE=0                              # login node: downloads allowed
mkdir -p "$HF_HUB_CACHE" "$TRANSFORMERS_CACHE"
IMAGES="$ADARQ_CACHE/coco_val2017"

step() { printf '\n\033[1m=== %s ===\033[0m\n' "$1"; }
step "cache: $ADARQ_CACHE  (HF_HOME=$HF_HOME)"
df -h "$ADARQ_CACHE" | tail -1

# -- 2. real CLIP vision tower ---------------------------------------------------------
step "downloading real CLIP: $CLIP_MODEL"
python3 - "$CLIP_MODEL" <<'PY'
import sys
from transformers import CLIPImageProcessor, CLIPVisionModel
mid = sys.argv[1]
CLIPImageProcessor.from_pretrained(mid)
m = CLIPVisionModel.from_pretrained(mid)
print(f"  cached {mid}: {sum(p.numel() for p in m.parameters())/1e6:.1f}M params")
PY

# -- 3. real images --------------------------------------------------------------------
step "downloading $NUM_IMAGES real COCO val2017 images -> $IMAGES"
python3 "$REPO/scripts/extract_clip_latents.py" \
    --out "$ADARQ_CACHE/prefetch_probe.pt" \
    --num-images "$NUM_IMAGES" \
    --model "$CLIP_MODEL" \
    --save-images "$IMAGES"
rm -f "$ADARQ_CACHE/prefetch_probe.pt" "$ADARQ_CACHE/prefetch_probe.pt.meta.json"
echo "  $(find "$IMAGES" -name '*.jpg' | wc -l) images cached"

# -- 4. gated weights (opt-in) ---------------------------------------------------------
if [ "$WANT_GATED" = "1" ]; then
  step "downloading GATED weights (requires prior 'hf auth login' + accepted licences)"
  python3 - <<'PY'
from huggingface_hub import snapshot_download
for repo in ("Qwen/Qwen2.5-VL-7B-Instruct", "black-forest-labs/FLUX.1-dev"):
    print(f"  {repo} ...", flush=True)
    snapshot_download(repo)          # raises on missing auth / unaccepted licence
    print(f"  cached {repo}")
PY
else
  step "skipping gated weights (pass --gated once Qwen2.5-VL / FLUX.1-dev are wired)"
fi

# -- 5. the offline env file compute nodes source --------------------------------------
cat > "$ADARQ_CACHE/adarq_env.sh" <<EOF
# Generated by scripts/prefetch_assets.sh — source this on OFFLINE compute nodes.
export ADARQ_CACHE="$ADARQ_CACHE"
export HF_HOME="$HF_HOME"
export HF_HUB_CACHE="$HF_HUB_CACHE"
export TRANSFORMERS_CACHE="$TRANSFORMERS_CACHE"
export ADARQ_IMAGES="$IMAGES"
# Fail loudly instead of hanging on a network call that cannot succeed:
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
EOF

step "done"
cat <<EOF
Compute-node usage (no internet required):

  source $ADARQ_CACHE/adarq_env.sh
  bash scripts/smoke_test.sh          # picks up \$ADARQ_IMAGES automatically

Nothing was written under \$HOME.
EOF
